In [15]:
#  Numpy Array Dimensions
import numpy as sr
a = sr.array(90)

print(a.ndim,"Dimension")
a = sr.array([10,20,30,40,50])
print(a)

print(a.ndim,"Dimension")
a = sr.array([[10,20],[30,40]])
print(a)
print(a.ndim,"Dimension")
a = sr.array([[[10,20,8],[30,40,3]],[[40,50,1],[60,70,8]]])
print(a)
print(a.ndim,"Dimension") 

a.shape

0 Dimension
[10 20 30 40 50]
1 Dimension
[[10 20]
 [30 40]]
2 Dimension
[[[10 20  8]
  [30 40  3]]

 [[40 50  1]
  [60 70  8]]]
3 Dimension


(2, 2, 3)

In [8]:
a = sr.array([10,20,30,40,50])
print(a)
print(a.ndim,"Dimension")

[10 20 30 40 50]
1 Dimension


In [11]:
# 1D to 2D and 3D
a = sr.array([10,20,30,40,50])
b = a.reshape(1,-1)
c = a.reshape(-1,1)
d = a.reshape(1,1,-1)
e = a.reshape(-1,1,1)
f = a.reshape(-2,1,1)

print(a)
print(a.ndim,"Dimension")
print(b)
print(b.ndim,"Dimension")
print(c)
print(c.ndim,"Dimension")
print(d)
print(d.ndim,"Dimension")
print(e)
print(e.ndim,"Dimension")
print(f)
print(f.ndim,"Dimension")

[10 20 30 40 50]
1 Dimension
[[10 20 30 40 50]]
2 Dimension
[[10]
 [20]
 [30]
 [40]
 [50]]
2 Dimension
[[[10 20 30 40 50]]]
3 Dimension
[[[10]]

 [[20]]

 [[30]]

 [[40]]

 [[50]]]
3 Dimension
[[[10]]

 [[20]]

 [[30]]

 [[40]]

 [[50]]]
3 Dimension


In [61]:
# 2D to 3D and 1D
a = sr.array([[10,20],[30,40],[50,60]])
b = a.reshape(1,-1)
# c = a.reshape(-1,1)
d = a.reshape(1,1,-1)
e = a.reshape(-1,1,1)
f = a.reshape(-1)

print(a)
print(a.ndim,"Dimension")
print(b)
print(b.ndim,"Dimension")
print(c)
print(c.ndim,"Dimension")
print(d)
print(d.ndim,"Dimension")
print(e)
print(e.ndim,"Dimension")
print(f)
print(f.ndim,"Dimension")
print(g)
print(g.ndim,"Dimension")


[[10 20 30 40 50 60]]
2 Dimension
[[10]
 [20]
 [30]
 [40]
 [50]
 [60]]
2 Dimension
[[[10 20 30 40 50 60]]]
3 Dimension
[[[10]]

 [[20]]

 [[30]]

 [[40]]

 [[50]]

 [[60]]]
3 Dimension
[10 20 30 40 50 60]
1 Dimension
[10 20 30 40 50 60]
1 Dimension


In [67]:
# 3D to 2D and 1D
a = sr.array([[[10,20],[30,40]],[[50,60],[70,80]]])
b = a.reshape(1,-1)
c = a.reshape(-1,1)
d = a.reshape(2,-1)
e = a.reshape(-1,2)
f = a.reshape(2,-2)
g = a.reshape(-1)

print(a)
print(a.ndim,"Dimension")
print(b)
print(b.ndim,"Dimension")
print(c)
print(c.ndim,"Dimension")
print(d)
print(d.ndim,"Dimension")
print(e)
print(e.ndim,"Dimension")
print(f)
print(f.ndim,"Dimension")
print(g)
print(g.ndim,"Dimension")

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
3 Dimension
[[10 20 30 40 50 60 70 80]]
2 Dimension
[[10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]]
2 Dimension
[[10 20 30 40]
 [50 60 70 80]]
2 Dimension
[[10 20]
 [30 40]
 [50 60]
 [70 80]]
2 Dimension
[[10 20 30 40]
 [50 60 70 80]]
2 Dimension
[10 20 30 40 50 60 70 80]
1 Dimension
