In [1]:
#  22-09-2025   NUMPY

import numpy


In [2]:
a = numpy.array([1,2,3,4,5,6])

print(a)

[1 2 3 4 5 6]


In [3]:
import numpy as sr
k=sr.array([101,102,103,104,105,106])
print(k)

[101 102 103 104 105 106]


In [5]:
print(sr.__version__)

2.1.3


In [6]:
print(type(k))

<class 'numpy.ndarray'>


In [11]:
# if no arrays is mentioned it is 0 dimension

import numpy as sr
a = sr.array(90)
print(a)
print(a.ndim)

90
0


In [24]:
import numpy as sr
a = sr.array([1,2,3,4,5])
print(a)
print(a.ndim)

[1 2 3 4 5]
1


In [15]:
import numpy as sr
a = sr.array([[10,20],[30,40]])
print(a)
print(a.ndim)

[[10 20]
 [30 40]]
2


In [16]:
import numpy as sr
a = sr.array([[[10,20],[30,40]],[[40,50],[60,70]]])
print(a)
print(a.ndim)

[[[10 20]
  [30 40]]

 [[40 50]
  [60 70]]]
3


In [25]:
import numpy as sr
a = sr.array([[[10,20],[30,40]],[[40,50],[60,70]]])
print(a)
print(a.ndim)

[[[10 20]
  [30 40]]

 [[40 50]
  [60 70]]]
3


In [19]:
import numpy as sr
a = sr.array([[10,20],[30,40]])
b = sr.array([[40,50],[60,70]])

add=a+b
add


array([[ 50,  70],
       [ 90, 110]])